version: "3"

services:
  db:
    container_name: raspberry-pg
    image: postgres:10
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - pgdata
      #- pgdata:/var/lib/postgresql/data

##  volumes:
#    pgdata:

